#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-prawn-manual_builder
Version  : 0.2.0
Release  : 4
URL      : https://rubygems.org/downloads/prawn-manual_builder-0.2.0.gem
Source0  : https://rubygems.org/downloads/prawn-manual_builder-0.2.0.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
BuildRequires : ruby
BuildRequires : rubygem-coderay
BuildRequires : rubygem-rdoc
Patch1: 0001-Fix-coderay-version.patch

%description
# Prawn::ManualBuilder
This library is used by Prawn to generate its self-documenting manual,
and could be used by third-party Prawn extensions to create manuals
for their functionality as well.

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n prawn-manual_builder-0.2.0
gem spec %{SOURCE0} -l --ruby > rubygem-prawn-manual_builder.gemspec
%patch1 -p1

%build
gem build rubygem-prawn-manual_builder.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
prawn-manual_builder-0.2.0.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/prawn-manual_builder-0.2.0.gem
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/cdesc-Example.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/colored_box-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/eval_code-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/example_header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/header-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/header_box-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/inner_box-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/list-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/load_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/load_package-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/load_page-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/package-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/prose-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/register_fonts-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/render_example-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/render_package_cover-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/render_section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/reset_settings-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/source_link-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/Example/stroke_axis-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/cdesc-ExampleFile.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/eval%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/filename-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/full_source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/generate_block_source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/introduction_text-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/package-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/parent_folder_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/parent_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/read_file-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleFile/source-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/cdesc-ExamplePackage.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/example-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/folder_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/intro-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/intro_block-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExamplePackage/section-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleSection/cdesc-ExampleSection.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleSection/example-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleSection/folder_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleSection/name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleSection/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleSection/package_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/ExampleSection/render-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/PrawnEncoder/begin_group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/PrawnEncoder/cdesc-PrawnEncoder.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/PrawnEncoder/end_group-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/PrawnEncoder/setup-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/PrawnEncoder/text_token-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/cdesc-ManualBuilder.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/document_class-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/manual_dir%3d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/ManualBuilder/manual_dir-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/Prawn/cdesc-Prawn.ri
/usr/lib64/ruby/gems/2.2.0/doc/prawn-manual_builder-0.2.0/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/COPYING
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/GPLv2
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/GPLv3
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/README.md
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/data/fonts/DejaVuSans.ttf
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/data/fonts/Dustismo_Roman.ttf
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/data/fonts/gkai00mp.ttf
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/lib/prawn/manual_builder.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/lib/prawn/manual_builder/example.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/lib/prawn/manual_builder/example_file.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/lib/prawn/manual_builder/example_package.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/lib/prawn/manual_builder/example_section.rb
/usr/lib64/ruby/gems/2.2.0/gems/prawn-manual_builder-0.2.0/lib/prawn/manual_builder/syntax_highlight.rb
/usr/lib64/ruby/gems/2.2.0/specifications/prawn-manual_builder-0.2.0.gemspec
